### ISSUE TITLE
Should Player be Separate from Creature

### ISSUE THREAD

**Issue by chrisabruce** [Sinono3/simple-roguelike#1]
Looking at the way the code is structured, it looks like you might want to consider separating out the player from the creatures list.  It looks like the player is treated differently in each System.  The aggression system is really treating player differently due to feature.

Just a thought.

**Comment by Sinono3** [comment]
According to my current design and view of the game, the player has to be a `Creature` for a more flexible approach such as buffs and debuffs to be applied equally to each creature and just to let the player be any creature they want... you could say, for a more immersive experience. This will also let the player be loaded from a normal Creature JSON file.
