### ISSUE TITLE
Consider Using Collections

### ISSUE THREAD

**Issue by chrisabruce** [Sinono3/simple-roguelike#2]
Not sure if you are aiming to build an ECS system, but at this size, I am not sure the extra work is worth it? 

In either case, you might want to make use of iterators and collections more.  They are super fast (sometimes faster than for loops).

For example:
You can do something like this in your `attack_queue` to iterate over inflictors:
```rust
fn attack_queue(state: &mut GameState) {
	for inflictor in state
		.creatures
		.iter_mut()
		.filter(|creature| creature.current_victims.len() > 0)
	{
		inflictor.name = "hello".to_string();
	}
```

**Comment by Sinono3** [comment]
The issue was covered by the last commit.
> This commit also addresses issue #2 indirectly due to the removal of the queue, but also by replacing an id check with an iterator in the player system.

**Comment by Sinono3** [comment]
The issue was covered by the last commit.
> This commit also addresses issue #2 indirectly due to the removal of the queue, but also by replacing an id check with an iterator in the player system.
