### ISSUE TITLE
Simplify Game Logic

### ISSUE THREAD

**Issue by chrisabruce** [Sinono3/simple-roguelike#3]
This is just a suggestion and might be other reasons for not adding extra functions to "objects", but I like to try and take some domain language and make it a little more implicit (the example can also be done functionally if desired):

The following:
```rust
fn attack_queue(state: &mut GameState) {
	for id in 0..state.creatures.len() {
		let (name, damage, victims) = {
			let inflictor = state.get_creature_mut(id);
			
			if inflictor.current_victims.len() < 1 {
				continue;
			}
```

Might be more clear if there was a function on `creature`, aka `inflictor` in this case...

```rust
fn attack_queue(state: &mut GameState) {
//...
			if inflictor.has_victims() {
				continue;
			}
```

By moving the `inflictor.current_victims.len() < 1` behind a `inflictor.has_victims()` makes the logic in one place. Maybe should be `inflictor.can_attack()`?

**Comment by Sinono3** [comment]
Solved as `Creature` no longer stores victims in a vector and the whole attack queue system has been scrapped for a better system: `hit()`, but I will be sure to apply these kinds of changes to future structs.
